# .aider.conf.yml
read:
  - .agent/rules/ai_behavior.md
  - CONTEXT.md

auto-commits: false  # We want manual control over commits to review them
dirty-commits: false # Ensure working directory is clean before coding
